### ISSUE TITLE
Minor bug 

### ISSUE THREAD

**Issue by AbhinavRajesh** [nandan-unni/Django-Blogging-App#1]
In file **Django-Blogging-App/templates/registration/create_username.html**
The input field is accepting username but the placeholder text is:
<p align="center">
<img height=250 width=250 src="https://user-images.githubusercontent.com/54738622/88068189-7f9c5300-cb8d-11ea-8466-734bdedfc4da.jpeg" />
</p>
Instead of "Enter your Password" it should be "Enter your pen name" or "Enter your username".

Code:

``` <input type="text"  name="username" id="username" placeholder="Enter your pen name">```
<p align="center">
OR
</p>

```<input type="text"  name="username" id="username" placeholder="Enter your username">```

**Comment by Nandan-unni-zz** [comment]
Thanks @AbhinavRajesh , I fixed the issue in the last commit
